services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha_backend_2025
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/rinha_backend_2025
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - "8080:${PORT}"
    depends_on:
      - database

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/rinha_backend_2025
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - "8081:${PORT}"
    depends_on:
      - database
