version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./.infra/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: rinha_backend_2025
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - PORT=8080
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - PORT=8081
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - payment-processor
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
